# Generated by Django 4.0.3 on 2022-05-26 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbbooking',
            name='classType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_type', to='escalada.classtype'),
        ),
        migrations.AddField(
            model_name='climbbooking',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
