# Generated by Django 4.0.3 on 2022-06-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='climber',
            new_name='climbers',
        ),
    ]
