# Generated by Django 4.0.3 on 2022-06-02 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='class_date',
            field=models.DateField(default=models.DateField(default=datetime.date.today)),
        ),
    ]
