# Generated by Django 4.0.3 on 2022-05-29 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0002_climbbooking_classtype_climbbooking_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('seatsAvailable', models.IntegerField(default=0)),
                ('classType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_type', to='escalada.classtype')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ClimbBooking',
        ),
    ]
