# Generated by Django 4.0.3 on 2022-06-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0002_rename_climber_enrollment_climbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='numberOfClasses',
            new_name='numberOfLessons',
        ),
    ]
