# Generated by Django 4.0.3 on 2022-06-02 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0002_alter_enrollment_class_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='class_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
