# Generated by Django 4.0.3 on 2022-06-01 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0002_alter_climbclass_lessonday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbclass',
            name='climbers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
