# Generated by Django 4.0.3 on 2022-06-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0003_rename_numberofclasses_coupon_numberoflessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='numberOfLessons',
            new_name='numberOfWeeks',
        ),
    ]
