# Generated by Django 4.0.3 on 2022-05-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0003_climbclass_delete_climbbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbclass',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
