# Generated by Django 4.0.3 on 2022-06-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0004_rename_numberoflessons_coupon_numberofweeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='begin_date',
        ),
    ]
