# Generated by Django 4.0.3 on 2022-06-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0005_remove_enrollment_begin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myCoupons',
            field=models.ManyToManyField(to='escalada.coupon'),
        ),
    ]
