# Generated by Django 4.0.3 on 2022-06-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0005_remove_climbclass_climbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbclass',
            name='startHour',
        ),
    ]
