# Generated by Django 4.0.3 on 2022-06-01 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0006_remove_climbclass_starthour'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbclass',
            name='startHour',
            field=models.IntegerField(default=36, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(47)]),
        ),
    ]
