# Generated by Django 4.0.3 on 2022-06-07 17:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0006_user_mycoupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='myCoupons',
        ),
        migrations.CreateModel(
            name='MyCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketsAvailable', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalada.coupon')),
            ],
        ),
    ]
