# Generated by Django 4.0.3 on 2022-06-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0007_remove_user_mycoupons_mycoupon'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mycoupon',
            constraint=models.UniqueConstraint(fields=('climber', 'coupon'), name='escalada_mycoupon_unique_relationships'),
        ),
    ]
