# Generated by Django 4.0.3 on 2022-06-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0007_climbclass_starthour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbclass',
            name='startHour',
            field=models.TimeField(),
        ),
    ]
