# Generated by Django 4.0.3 on 2022-06-07 21:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0008_mycoupon_escalada_mycoupon_unique_relationships'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbPassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('maxClimbers', models.IntegerField(default=1)),
                ('onlyStaffEditable', models.BooleanField(default=True)),
                ('durationInHours', models.IntegerField(default=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='classtype',
            name='isRecurring',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='classType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escalada.classtype'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='numberOfWeeks',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('concept', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('climber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='climbPassType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escalada.climbpasstype'),
        ),
    ]
