# Generated by Django 4.0.3 on 2022-06-02 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0008_alter_climbclass_starthour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climbclass',
            name='startHour',
        ),
        migrations.AddField(
            model_name='climbclass',
            name='begin_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
