# Generated by Django 4.0.3 on 2022-06-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0009_climbpasstype_remove_classtype_isrecurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='classType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escalada.classtype'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='climbPassType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escalada.climbpasstype'),
        ),
    ]
