# Generated by Django 4.0.3 on 2022-06-07 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0011_rename_enrollment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycoupon',
            name='ticketsAvailable',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
