# Generated by Django 4.0.3 on 2022-06-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0012_alter_mycoupon_ticketsavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycoupon',
            name='recentlyBought',
            field=models.BooleanField(default=True),
        ),
    ]
