# Generated by Django 4.0.3 on 2022-06-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0013_mycoupon_recentlybought'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbclass',
            name='is_Available',
            field=models.BooleanField(default=True),
        ),
    ]
