# Generated by Django 4.0.3 on 2022-06-10 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0014_climbclass_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='climbers',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
