# Generated by Django 4.0.3 on 2022-06-10 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0015_alter_lesson_climbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbclass',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
