# Generated by Django 4.0.3 on 2022-06-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0016_climbclass_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbclass',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
