# Generated by Django 4.0.3 on 2022-06-11 23:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0017_alter_climbclass_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeClimb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField(default=datetime.date.today)),
                ('climbPassType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalada.climbpasstype')),
                ('climbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeClimber', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalada.coupon')),
            ],
        ),
    ]
