# Generated by Django 4.0.3 on 2022-06-11 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0018_freeclimb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeclimb',
            name='class_date',
        ),
        migrations.AddField(
            model_name='freeclimb',
            name='class_datetime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
