# Generated by Django 4.0.3 on 2022-06-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0019_remove_freeclimb_class_date_freeclimb_class_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclimb',
            name='class_datetime',
            field=models.DateTimeField(),
        ),
    ]
