# Generated by Django 4.0.3 on 2022-06-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0020_alter_freeclimb_class_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeclimb',
            old_name='climbers',
            new_name='climber',
        ),
    ]
