# Generated by Django 4.0.3 on 2022-06-13 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0021_rename_climbers_freeclimb_climber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeclimb',
            name='class_datetime',
        ),
        migrations.AddField(
            model_name='freeclimb',
            name='begin_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='freeclimb',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='freeclimb',
            name='end_time',
            field=models.TimeField(default=datetime.time(2, 0)),
        ),
    ]
