# Generated by Django 4.0.3 on 2022-06-14 21:39

import datetime
from django.db import migrations, models
import escalada.models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0022_remove_freeclimb_class_datetime_freeclimb_begin_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekdaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', escalada.models.DayOfTheWeekField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('opening_hour', models.TimeField(default=datetime.time(0, 0))),
                ('closing_hour', models.TimeField(default=datetime.time(23, 59))),
                ('special_schedule', models.BooleanField(default=False)),
            ],
        ),
    ]
