# Generated by Django 4.0.3 on 2022-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0023_weekdayschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdayschedule',
            name='special_day',
            field=models.DateField(default='1912-06-23'),
        ),
    ]
