# Generated by Django 4.0.3 on 2022-06-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0024_weekdayschedule_special_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdayschedule',
            name='special_day',
        ),
        migrations.RemoveField(
            model_name='weekdayschedule',
            name='special_schedule',
        ),
        migrations.AddConstraint(
            model_name='weekdayschedule',
            constraint=models.UniqueConstraint(fields=('weekday',), name='escalada_weekdayschedule_unique_relationships'),
        ),
    ]
