# Generated by Django 4.0.3 on 2022-06-14 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0025_remove_weekdayschedule_special_day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weekdayschedule',
            name='escalada_weekdayschedule_unique_relationships',
        ),
    ]
