# Generated by Django 4.0.3 on 2022-06-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalada', '0027_alter_weekdayschedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdayschedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
